server:
  port: 8092

spring:
  threads:
    virtual:
      enabled: true

  r2dbc:
    url: ${APP_R2DBC_URL:r2dbc:postgresql://localhost:5442/ai_rag_platform?schema=mcp_gateway}
    username: ${APP_DATASOURCE_USERNAME:postgres}
    password: ${APP_DATASOURCE_PASSWORD:123456}

  flyway:
    url: ${APP_DATASOURCE_URL:jdbc:postgresql://localhost:5442/ai_rag_platform}
    user: ${APP_DATASOURCE_USERNAME:postgres}
    password: ${APP_DATASOURCE_PASSWORD:123456}

logging:
  level:
    "[com.silver.ai.mcpgateway]": DEBUG

redis:
  sdk:
    config:
      host: ${APP_REDIS_HOST:localhost}
      port: ${APP_REDIS_PORT:6379}
      password: ${APP_REDIS_PASSWORD:}
