export interface SystemSettings {
  intentConfidenceThreshold: number;
  intentEnabled: boolean;
  rewriteEnabled: boolean;
  hydeEnabled: boolean;
  rewriteContextRounds: number;
  multiPathRetrievalEnabled: boolean;
  rerankTopK: number;
  retrievalTimeoutSeconds: number;
  deduplicatePrefixLength: number;
  rerankerServiceEnabled: boolean;
  rerankerBaseUrl: string;
  rerankerModel: string;
  rerankerApiKeyMasked?: string;
  rerankerApiKey?: string;
  rerankerApiKeyConfigured: boolean;
  clearRerankerApiKey?: boolean;
  memoryFullRounds: number;
  memoryMaxChars: number;
  memorySummaryThreshold: number;
  modelFallbackEnabled: boolean;
  modelMaxRetries: number;
  healthCheckIntervalMinutes: number;
  toolAutoExecuteThreshold: number;
  toolSemanticRetrievalEnabled: boolean;
  toolRetrievalTopK: number;
  toolRetrievalThreshold: number;
  toolFallbackEnabled: boolean;
  traceSampleRate: number;
  traceEnabled: boolean;
  auxiliaryProviderId: number | null;
  suggestionPrompt: string;
}
